### ISSUE TITLE
Pause after vid is done.

### ISSUE THREAD

**Issue by gerro-abarabar** [ree1261/pyvidplayer#6]
I want it to pause when the vid is done, how should I achieve that?

**Comment by anrayliu** [comment]
the video should stop playing on it's own when it's done

**Comment by gerro-abarabar** [comment]
How to pause after vid finishes, I don't want it to stop.

**Comment by anrayliu** [comment]
I'm not sure what you mean. If the video is finished playing, it won't matter whether or not it's paused. If you don't want it to stop, you can restart it.

**Comment by gerro-abarabar** [comment]
No, it stands on the last frame when done, or be able to be manually paused by input or more.

**Comment by anrayliu** [comment]
Are you saying you want to video to restart after it's done?

**Comment by gerro-abarabar** [comment]
The first part yes, but I would like to add a pause function and also a boolean that says when the video ends, instead of just showing a black background.

**Comment by anrayliu** [comment]
I believe there's a variable called active (check the docs) that tells you if the video is finished playing or not. You can use that to do what you want with the video at the end. As for restarting, you can use the restart function

**Comment by gerro-abarabar** [comment]
I see, but I would still like a pause function, where it just stops at the frame picked.

**Comment by anrayliu** [comment]
Can you not use the seek function to go somewhere and then pause it?
